#!/usr/bin/env ruby

require 'fileutils'

xcode_locations = [
  "/Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation",
  "/Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/Versions/A/DVTKit",
  "/Applications/Xcode.app/Contents/SharedFrameworks/DTGraphKit.framework/Versions/A/DTGraphKit",
  "/Applications/Xcode.app/Contents/SharedFrameworks/DVTDeveloperModeHelper.framework/Versions/A/DVTDeveloperModeHelper",
  "/Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation",
  "/Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/A/IDEKit",
  "/Applications/Xcode.app/Contents/PlugIns/"]

FileUtils.mkdir_p("docs")

for location in xcode_locations
  is_dir = !File.file?(location)

  if is_dir
    for file in Dir[location + "*"]
      filename = File.basename(file, ".*")
      dir = "docs/" + File.basename(location)
      FileUtils.mkdir_p(dir)
      `class-dump '#{file}' > #{dir}/#{filename}.h`
    end
  else
    `class-dump '#{location}' > docs/#{File.basename(location)}.h`
  end
end
