/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/DebuggerLLDBService.ideplugin/Contents/MacOS/DebuggerLLDBService
 * UUID: 4685EFE8-BD6C-38EC-A5F0-5D5D5A9C5985
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1185.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 *       Run path: @loader_path/../../../
 *               = /Applications/Xcode.app/Contents/PlugIns
 *       Run path: @loader_path/../../Library/PrivateFrameworks/
 *               = /Applications/Xcode.app/Contents/PlugIns/DebuggerLLDBService.ideplugin/Library/PrivateFrameworks
 */

// Not exported
@interface DBGLLDBDebugLocalService : IDERunDeviceService
{
}

+ (id)_loadDebuggerExtension;
+ (id)capability;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;

@end

// Not exported
@interface DBGLLDBRunLocalService : IDERunDeviceService
{
}

+ (id)capability;
- (id)operationWorkerWithLaunchSession:(id)arg1 error:(id *)arg2;
- (id)capabilitySequenceForLaunchSession:(id)arg1;

@end

