/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct NSObject {
    Class _field1;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/DebuggerFoundation.ideplugin/Contents/MacOS/DebuggerFoundation
 * UUID: DF93DC84-0802-3E79-9EC4-C4423D0F5E77
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 2083.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol DBGLazyObservableDictionaryDelegate <NSObject>
- (id)valueForKey:(id)arg1 forLazyDictionary:(id)arg2;
@end

@protocol DVTCancellable <NSObject>
@property(readonly, getter=isCancelled) BOOL cancelled;
- (void)cancel;
@end

@protocol IDEDataValue <NSObject>
@property(readonly) BOOL childValuesCountValid;
@property(readonly) NSArray *childValues;
@property(readonly) BOOL hasChildValues;
@property(readonly) BOOL inScope;
@property(readonly) NSAttributedString *primitiveFormattedSummary;
@property(readonly) NSAttributedString *formattedSummary;
@property(readonly) BOOL typeHasChanged;
@property(readonly) NSString *type;
@property(readonly) BOOL valueHasChanged;
@property(readonly) BOOL isValueEditable;
@property(copy) NSString *value;
@property(readonly) NSString *name;

@optional
@property(readonly) BOOL treatSummaryAsValue;
@end

@protocol IDEDebugCompressionStrategy <NSObject>
+ (id)genericMaskFilePathWithColorsInRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
+ (id)maskFilePathForUserCodeWithColorsInRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
+ (id)maskFilePathForModulePathString:(id)arg1 withColorsInRed:(double *)arg2 green:(double *)arg3 blue:(double *)arg4 alpha:(double *)arg5;
- (id)compressStackFrames:(id)arg1 level:(unsigned long long)arg2;
@end

@protocol IDEDebugNavigableModel <NSObject>
@property(readonly) IDELaunchSession *launchSession;
@property(readonly) NSString *associatedProcessUUID;
@end

@protocol IDEDebugProcess <IDEDebugNavigableModel>
@property(copy, nonatomic) NSString *name;
- (id)contentDelegateUIExtensionIdentifier;
@end

@protocol IDEDebugSession <NSObject>
@property(getter=isPausedForScripting) BOOL pausedForScripting;
@property(readonly) NSMutableArray *loadedSharedLibraries;
@property(readonly) DVTTextDocumentLocation *instructionPointerLocation;
@property(readonly) BOOL breakpointsActivated;
@property(readonly) id <IDEDebugProcess> process;
@property(readonly) int coalescedState;
@property int state;
- (struct _NSRange)rangeOfExpressionForFullTextAtPrompt:(id)arg1;
- (BOOL)canContinueToLocation:(id)arg1 withinBlockAtRange:(struct _NSRange)arg2;
- (BOOL)consoleShouldTrackInputHistory;
- (void)loadDebugSymbolsForSharedLibrary:(id)arg1;
- (BOOL)shouldAcceptFromDebugSession:(id)arg1 error:(id *)arg2;
- (BOOL)shouldRelinquishToDebugSession:(id)arg1 error:(id *)arg2;
- (void)executeDebuggerCommand:(id)arg1 threadID:(unsigned long long)arg2 frameID:(unsigned long long)arg3;
- (void)requestStop:(struct NSObject *)arg1;
- (void)requestContinueToLocation:(id)arg1 inContext:(struct NSObject *)arg2;
- (void)requestContinue:(struct NSObject *)arg1;
- (void)requestPause:(struct NSObject *)arg1;
- (void)requestStepOverSuspendOtherThreads:(struct NSObject *)arg1;
- (void)requestStepInSuspendOtherThreads:(struct NSObject *)arg1;
- (void)requestStepOverInstruction:(struct NSObject *)arg1;
- (void)requestStepIntoInstruction:(struct NSObject *)arg1;
- (void)requestStepOut:(struct NSObject *)arg1;
- (void)requestStepOverLine:(struct NSObject *)arg1;
- (void)requestStepIn:(struct NSObject *)arg1;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@optional
- (id)debugDescription;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface DBGDebugSession : NSObject <IDEDebugSession>
{
    IDELaunchSession *_launchSession;
    IDERunOperationWorker *_debugLauncher;
    int _state;
    int _coalescedState;
    BOOL _pausedForScripting;
    DBGProcess *_targetProcess;
    BOOL _hasExitCode;
    long long _exitCode;
    BOOL _breakpointsActivated;
    id <DBGDebugSessionBreakpointDelegate> _breakpointDelegate;
    id <DBGDebugSessionBreakpointLocationDelegate> _breakpointLocationDelegate;
    NSMapTable *_breakpointsToTokens;
    NSMapTable *_watchpointsToTokens;
    DVTTextDocumentLocation *_instructionPointerLocation;
    DVTTextDocumentLocation *_instructionPointerLocationForDisassembly;
    BOOL _lazySymbolLoadingEnabled;
    BOOL _debuggerShouldAttachToTarget;
    IDEConsoleAdaptor *_debuggerConsoleAdapter;
    NSMutableArray *_loadedSharedLibraries;
    NSMutableSet *_dataValuesObservers;
    DVTMapTable *_breakpointsToIdentifiers;
    DVTMapTable *_watchpointsToIdentifiers;
    DVTDispatchLock *_breakpointsAndWatchpointsToIdentifiersLock;
    NSError *_alertError;
    int _logFD;
    NSDate *_loggingInitializedDate;
    id <DVTObservingToken> _targetControlStateObservingToken;
    id <DVTObservingToken> _breakpontsActivationObservingToken;
    id <DVTObservingToken> _breakpointListObserverToken;
}

+ (id)createErrorForFailureToLaunchExecutable:(id)arg1 launchSession:(id)arg2;
+ (id)keyPathsForValuesAffectingBreakpointsActivated;
+ (id)keyPathsForValuesAffectingProcess;
+ (void)initialize;
@property(readonly) BOOL debuggerShouldAttachToTarget; // @synthesize debuggerShouldAttachToTarget=_debuggerShouldAttachToTarget;
@property(getter=isLazySymbolLoadingEnabled) BOOL lazySymbolLoadingEnabled; // @synthesize lazySymbolLoadingEnabled=_lazySymbolLoadingEnabled;
@property(readonly) NSDate *loggingInitializedDate; // @synthesize loggingInitializedDate=_loggingInitializedDate;
@property(copy) NSError *alertError; // @synthesize alertError=_alertError;
@property(retain) id <DBGDebugSessionBreakpointLocationDelegate> breakpointLocationDelegate; // @synthesize breakpointLocationDelegate=_breakpointLocationDelegate;
@property(retain, nonatomic) id <DBGDebugSessionBreakpointDelegate> breakpointDelegate; // @synthesize breakpointDelegate=_breakpointDelegate;
@property(retain) IDEConsoleAdaptor *debuggerConsoleAdaptor; // @synthesize debuggerConsoleAdaptor=_debuggerConsoleAdapter;
@property(copy) DVTTextDocumentLocation *instructionPointerLocationForDisassembly; // @synthesize instructionPointerLocationForDisassembly=_instructionPointerLocationForDisassembly;
@property(copy) DVTTextDocumentLocation *instructionPointerLocation; // @synthesize instructionPointerLocation=_instructionPointerLocation;
@property(retain) IDERunOperationWorker *debugLauncher; // @synthesize debugLauncher=_debugLauncher;
@property(readonly) IDELaunchSession *launchSession; // @synthesize launchSession=_launchSession;
@property long long exitCode; // @synthesize exitCode=_exitCode;
@property BOOL hasExitCode; // @synthesize hasExitCode=_hasExitCode;
@property(retain) DBGProcess *targetProcess; // @synthesize targetProcess=_targetProcess;
@property(getter=isPausedForScripting) BOOL pausedForScripting; // @synthesize pausedForScripting=_pausedForScripting;
@property int coalescedState; // @synthesize coalescedState=_coalescedState;
@property int state; // @synthesize state=_state;
- (BOOL)isWatchpointValid:(id)arg1;
- (BOOL)isBreakpointValid:(id)arg1;
- (void)setIdentifier:(unsigned long long)arg1 forWatchpoint:(id)arg2;
- (unsigned long long)identifierForWatchpoint:(id)arg1;
- (id)watchpointForIdentifier:(unsigned long long)arg1;
- (void)setIdentifier:(unsigned long long)arg1 forBreakpoint:(id)arg2;
- (unsigned long long)identifierForBreakpoint:(id)arg1;
- (id)breakpointForIdentifier:(unsigned long long)arg1;
@property(readonly) NSString *devicePathSubstitutionPairsString;
- (void)logDebugStringWithTimestampUsingFormat:(id)arg1;
- (void)logDebugStringWithFormat:(id)arg1;
- (void)logDebugStringWithTimestamp:(id)arg1;
- (void)logDebugString:(id)arg1;
@property(readonly) BOOL isLoggingEnabled;
- (BOOL)initializeLogging;
@property(readonly) NSString *logFilename;
@property(readonly) NSString *logSuffix;
- (struct _NSRange)rangeOfExpressionForFullTextAtPrompt:(id)arg1;
- (id)commandsExpectingExpressions;
- (unsigned long long)availableCompletionTypes:(unsigned long long)arg1 fullTextAfterPrompt:(id)arg2;
- (BOOL)supportsSteppingIntoCallSymbol;
- (BOOL)supportsWatchpoints;
- (BOOL)canContinueToLocation:(id)arg1 withinBlockAtRange:(struct _NSRange)arg2;
- (id)localizedStringForState:(int)arg1;
- (void)completeString:(id)arg1 resultHandler:(id)arg2;
- (void)requestPermissionForPoOfDataValue:(id)arg1;
- (void)deregisterDataValuesObserver:(id)arg1;
- (void)registerDataValuesObserver:(id)arg1;
@property(readonly) BOOL hasDataValuesObservers;
- (id)supportedDataValueFormatsForDataValue:(id)arg1;
- (BOOL)consoleShouldTrackInputHistory;
- (id)pathToInstrospectionSupportDyLib;
- (void)loadDebugSymbolsForSharedLibrary:(id)arg1;
- (void)executeDebuggerCommand:(id)arg1 threadID:(unsigned long long)arg2 frameID:(unsigned long long)arg3;
- (void)requestMovePCInStackFrame:(id)arg1 toLineNumber:(unsigned long long)arg2;
@property(readonly) BOOL supportsPCAnnotationDragging;
@property(readonly) BOOL supportsMultiplePCAnnotation;
- (void)requestContinueToLocation:(id)arg1 inContext:(struct NSObject *)arg2;
- (void)requestStepIntoCallSymbol:(id)arg1 atLocation:(id)arg2 inContext:(struct NSObject *)arg3;
- (void)printDescriptionOfDataValueToConsole:(id)arg1 runAllThreads:(BOOL)arg2;
- (BOOL)shouldAcceptFromDebugSession:(id)arg1 error:(id *)arg2;
- (BOOL)shouldRelinquishToDebugSession:(id)arg1 error:(id *)arg2;
- (void)requestStepOverSuspendOtherThreads:(struct NSObject *)arg1;
- (void)requestStepInSuspendOtherThreads:(struct NSObject *)arg1;
- (void)requestStepOverInstruction:(struct NSObject *)arg1;
- (void)requestStepIntoInstruction:(struct NSObject *)arg1;
- (void)requestStop:(struct NSObject *)arg1;
- (void)requestContinue:(struct NSObject *)arg1;
- (void)requestPause:(struct NSObject *)arg1;
- (void)requestStepOut:(struct NSObject *)arg1;
- (void)requestStepOverLine:(struct NSObject *)arg1;
- (void)requestStepIn:(struct NSObject *)arg1;
- (void)_delayedSetState;
- (void)_recreateBreakpointIfNeccessary:(id)arg1;
- (void)_createBreakpointIfNeccessary:(id)arg1;
- (void)_handleTargetProcessStateChanged;
- (void)_handleLaunchSessionTargetOutputStateChanged;
- (void)_outputExitString;
- (void)_handleExceptionBreakpointExceptionNameChanged:(id)arg1;
- (void)_handleExceptionBreakpointStopOnStyleChanged:(id)arg1;
- (void)_handleExceptionBreakpointScopeChanged:(id)arg1;
- (void)_handleSymbolicBreakpointModuleNameChanged:(id)arg1;
- (void)_handleSymbolicBreakpointSymbolNameChanged:(id)arg1;
- (void)_handleFileBreakpointLocationChanged:(id)arg1;
- (void)_handleBreakpointIgnoreCountChanged:(id)arg1;
- (void)_handleBreakpointConditionChanged:(id)arg1;
- (void)_handleBreakpointEnablementChanged:(id)arg1;
- (void)_handleBreakpointActivationChanged;
- (void)_handleBreakpointLocationsRemoved:(id)arg1;
- (void)_handleBreakpointLocationsAdded:(id)arg1;
- (void)_handleBreakpointLocationChanges:(id)arg1;
- (void)_handleBreakpointsDeleted:(id)arg1;
- (void)_handleBreakpointsCreated:(id)arg1;
- (void)_handleBreakpointsListChanged:(id)arg1;
- (void)_removeWatchpointObservers:(id)arg1;
- (void)_addWatchpointObservers:(id)arg1;
- (void)_removeBreakpointObservers:(id)arg1;
- (void)_addBreakpointObservers:(id)arg1;
@property(readonly) BOOL breakpointsActivated; // @synthesize breakpointsActivated=_breakpointsActivated;
@property(readonly) IDEBreakpointManager *breakpointManager;
@property(readonly) id <IDEDebugProcess> process;
- (void)cleanUp;
- (id)initWithDebugLauncher:(id)arg1;

// Remaining properties
@property(readonly) NSMutableArray *loadedSharedLibraries; // @dynamic loadedSharedLibraries;

@end

@interface DBGProcess : NSObject <IDEDebugProcess>
{
    DBGDebugSession *_parentDebugSession;
    NSString *_associatedProcessUUID;
    int _controlState;
    NSArray *_threads;
    BOOL _threadsAutoRefreshStackFramesDone;
    NSMutableSet *_threadsAutoRefreshStackFrames;
    NSMutableSet *_codeModules;
    NSMutableDictionary *_codeModuleForPathTable;
    DBGThread *_currentThread;
    DBGStackFrame *_currentStackFrame;
    NSString *_name;
    int _PID;
    BOOL _usesPIDInName;
    BOOL _allSameSchemes;
    NSMutableArray *_memoryDatas;
}

+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingThreads;
+ (void)initialize;
@property BOOL threadsAutoRefreshStackFramesDone; // @synthesize threadsAutoRefreshStackFramesDone=_threadsAutoRefreshStackFramesDone;
@property(nonatomic) BOOL allSameSchemes; // @synthesize allSameSchemes=_allSameSchemes;
@property(nonatomic) BOOL usesPIDInName; // @synthesize usesPIDInName=_usesPIDInName;
@property(nonatomic) int PID; // @synthesize PID=_PID;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) DBGStackFrame *currentStackFrame; // @synthesize currentStackFrame=_currentStackFrame;
@property(retain, nonatomic) DBGThread *currentThread; // @synthesize currentThread=_currentThread;
@property(copy, nonatomic) NSArray *threads; // @synthesize threads=_threads;
@property(nonatomic) int controlState; // @synthesize controlState=_controlState;
@property(readonly) NSString *associatedProcessUUID; // @synthesize associatedProcessUUID=_associatedProcessUUID;
@property(readonly) DBGDebugSession *parentDebugSession; // @synthesize parentDebugSession=_parentDebugSession;
- (id)_stackFrameInThread:(id)arg1 frameID:(unsigned long long)arg2;
- (id)stackFrameForThreadID:(unsigned long long)arg1 frameID:(unsigned long long)arg2;
- (void)removeMemoryData:(id)arg1;
- (void)autoUpdateAllMemoryDatas;
- (id)readMemoryAtAddress:(unsigned long long)arg1 numberOfBytes:(unsigned long long)arg2 resultHandler:(id)arg3;
- (void)rawMemoryDataForAddressExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2 resultHandler:(id)arg3;
- (id)memoryDataForUUID:(id)arg1;
- (id)memoryDataForAddressOfExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2;
- (void)_handleCodeModuleChange:(id)arg1;
- (id)codeModuleForPath:(id)arg1;
- (BOOL)hasThreadsAutoRefreshStackFrames;
- (void)deregisterThreadAutoRefreshesStackFrames:(id)arg1;
- (void)registerThreadAutoRefreshesStackFrames:(id)arg1;
- (BOOL)_isCurentThreadCrashedStoppedForAnExceptionBreakpointOrStoppedForFatalSignal;
- (BOOL)_shouldLookForStackFrameWithDebugSymbols;
- (void)setInitialCurrentStackFrame;
@property(readonly) NSString *displayStatus;
@property(readonly) IDELaunchSession *launchSession;
- (id)initWithDebugSession:(id)arg1;
- (void)_detectNameConflict:(char *)arg1 sameScheme:(char *)arg2 forLaunchSession:(id)arg3 inLaunchSessions:(id)arg4 add:(BOOL)arg5;
- (void)_detectNameConflict:(char *)arg1 sameScheme:(char *)arg2 forLaunchSession:(id)arg3 otherLaunchSession:(id)arg4;
- (id)contentDelegateUIExtensionIdentifier;

// Remaining properties
@property(copy) NSSet *codeModules; // @dynamic codeModules;
@property(readonly) NSArray *memoryDatas; // @dynamic memoryDatas;
@property(copy) NSMutableSet *mutableCodeModules; // @dynamic mutableCodeModules;
@property(retain) NSMutableArray *mutableMemoryDatas; // @dynamic mutableMemoryDatas;

@end

@interface DBGReadMemoryCancellableToken : NSObject <DVTCancellable>
{
    BOOL _isCancelled;
}

- (BOOL)isCancelled;
- (void)cancel;

@end

@interface DBGThread : NSObject <IDEDebugNavigableModel>
{
    DBGProcess *_parentProcess;
    NSNumber *_uniqueID;
    NSString *_threadName;
    NSString *_queueName;
    int _state;
    int _stopReason;
    NSString *_lastReasonStopped;
    NSString *_threadDisplayName;
    BOOL _staleThreadDisplayName;
    NSString *_queueDisplayName;
    BOOL _staleQueueDisplayName;
    NSMutableArray *_stackFrames;
    BOOL _hasInitializedStackFrames;
    BOOL _autoRefreshStackFramesWhenPaused;
    BOOL _userSuspended;
}

+ (id)keyPathsForValuesAffectingStopped;
+ (void)initialize;
@property int stopReason; // @synthesize stopReason=_stopReason;
@property(copy, nonatomic) NSString *lastReasonStopped; // @synthesize lastReasonStopped=_lastReasonStopped;
@property BOOL userSuspended; // @synthesize userSuspended=_userSuspended;
@property BOOL autoRefreshStackFramesWhenPaused; // @synthesize autoRefreshStackFramesWhenPaused=_autoRefreshStackFramesWhenPaused;
@property BOOL hasInitializedStackFrames; // @synthesize hasInitializedStackFrames=_hasInitializedStackFrames;
@property(nonatomic) int state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *queueName; // @synthesize queueName=_queueName;
@property(copy, nonatomic) NSString *threadName; // @synthesize threadName=_threadName;
@property(readonly) NSNumber *uniqueID; // @synthesize uniqueID=_uniqueID;
@property(readonly) DBGProcess *parentProcess; // @synthesize parentProcess=_parentProcess;
- (void)requestUnsuspend;
- (void)requestSuspend;
- (void)requestStackFrames:(unsigned long long)arg1 resultQueue:(struct dispatch_queue_s *)arg2 resultHandler:(id)arg3;
- (BOOL)refreshStackFrames;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)_inferStateFromStackFrames:(id)arg1;
- (void)_inferState;
- (void)getLocalStackFrames:(id *)arg1 range:(struct _NSRange)arg2;
- (id)objectInLocalStackFramesAtIndex:(unsigned long long)arg1;
- (unsigned long long)countOfLocalStackFrames;
- (id)primitiveStackFrames;
@property(copy) NSArray *stackFrames; // @dynamic stackFrames;
@property(readonly, getter=isStopped) BOOL stopped;
@property(readonly) NSString *queueDisplayName; // @dynamic queueDisplayName;
@property(readonly) NSString *threadDisplayName; // @dynamic threadDisplayName;
- (id)description;
@property(readonly) IDELaunchSession *launchSession;
@property(readonly) NSString *associatedProcessUUID;
- (id)initWithParentProcess:(id)arg1 uniqueID:(id)arg2;

// Remaining properties
@property(readonly) NSMutableArray *mutableStackFrames; // @dynamic mutableStackFrames;

@end

@interface DBGStackFrame : NSObject <IDEDebugNavigableModel>
{
    DBGThread *_parentThread;
    DBGCodeModule *_module;
    NSNumber *_frameNumber;
    NSNumber *_framePointer;
    NSString *_name;
    NSString *_displayName;
    BOOL _hasSymbols;
    NSURL *_fileURL;
    NSNumber *_lineNumber;
    NSString *_instructionPointerAddressString;
    DBGDataValue *_returnValue;
    BOOL _returnValueIsValid;
    DBGDisassemblyInstructionList *_disassembly;
    id <DBGStackFrameDelegate> _delegate;
    id <DVTObservingToken> _debugSessionStateObserver;
}

+ (id)keyPathsForValuesAffectingDisassemblyURL;
+ (id)keyPathsForValuesAffectingDisplayName;
+ (id)uninitializedStackFrameForThread:(id)arg1 withFrameNumber:(id)arg2;
@property(retain) id <DBGStackFrameDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) DBGDisassemblyInstructionList *disassembly; // @synthesize disassembly=_disassembly;
@property(retain) DBGCodeModule *module; // @synthesize module=_module;
@property BOOL returnValueIsValid; // @synthesize returnValueIsValid=_returnValueIsValid;
@property(copy) NSString *instructionPointerAddressString; // @synthesize instructionPointerAddressString=_instructionPointerAddressString;
@property(copy) NSNumber *lineNumber; // @synthesize lineNumber=_lineNumber;
@property(copy) NSURL *fileURL; // @synthesize fileURL=_fileURL;
@property BOOL hasSymbols; // @synthesize hasSymbols=_hasSymbols;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy) NSNumber *framePointer; // @synthesize framePointer=_framePointer;
@property(copy, nonatomic) NSNumber *frameNumber; // @synthesize frameNumber=_frameNumber;
@property(retain) DBGThread *parentThread; // @synthesize parentThread=_parentThread;
- (void)requestDataValueForExpression:(id)arg1 atBlockStartAddress:(id)arg2 onQueue:(struct dispatch_queue_s *)arg3 withResultBlock:(id)arg4;
- (void)requestDataValueForSymbol:(id)arg1 symbolKind:(id)arg2 atLocation:(id)arg3 onQueue:(struct dispatch_queue_s *)arg4 withResultBlock:(id)arg5;
@property(readonly) NSURL *disassemblyURL;
- (void)_provideCachedDisassemblyOnMainThread:(id)arg1;
- (void)_doRequestDissassembly:(id)arg1;
- (void)requestDisassembly:(id)arg1;
- (void)primitiveSetReturnValueIsValid:(BOOL)arg1;
- (void)primitiveSetReturnValue:(id)arg1;
@property(retain) DBGDataValue *returnValue; // @synthesize returnValue=_returnValue;
- (void)primitiveSetInstructionPointerAddressString:(id)arg1;
@property(readonly) NSString *displayName; // @synthesize displayName=_displayName;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly) IDELaunchSession *launchSession;
@property(readonly) NSString *associatedProcessUUID;
- (id)initWithParentThread:(id)arg1 frameNumber:(id)arg2 framePointer:(id)arg3 name:(id)arg4;

// Remaining properties
@property(readonly) NSArray *arguments; // @dynamic arguments;
@property(readonly) NSArray *fileStatics; // @dynamic fileStatics;
@property(readonly) NSArray *locals; // @dynamic locals;
@property(readonly) NSArray *registers; // @dynamic registers;

@end

@interface DBGDisassemblyURLParts : NSObject
{
    int _processID;
    unsigned long long _threadID;
    unsigned long long _frameID;
}

+ (id)urlParts:(id)arg1;
+ (BOOL)isDisassemblyURL:(id)arg1;
@property(readonly) unsigned long long frameID; // @synthesize frameID=_frameID;
@property(readonly) unsigned long long threadID; // @synthesize threadID=_threadID;
@property(readonly) int processID; // @synthesize processID=_processID;
- (id)_initWithProcessID:(int)arg1 threadID:(unsigned long long)arg2 frameID:(unsigned long long)arg3;

@end

@interface DBGDataValue : NSObject <DBGLazyObservableDictionaryDelegate, IDEDataValue>
{
    DBGStackFrame *_stackFrame;
    DBGDataType *_dynamicType;
    DBGDataType *_previousDynamicType;
    int _valueValidity;
    BOOL _containsFunctionExpressions;
    DBGDataValueSummaryFormatter *_summaryFormatter;
    NSMutableSet *_requestedChildrenByName;
    DBGLazyObservableDictionary *_lazyChildValuesByName;
    BOOL _needToUpdateSummaryFormatter;
    id <DVTObservingToken> _childValuesObservationToken;
    NSAttributedString *_unescapedAttributedFormattedSummary;
    NSAttributedString *_escapedAttributedFormattedSummary;
    id <DVTObservingToken> _valueObserver;
    id <DVTObservingToken> _inScopeObserver;
}

+ (id)summaryUnavailableAttributedString;
+ (id)summaryUnavailableString;
+ (id)keyPathsForValuesAffectingFormattedSummary;
+ (id)keyPathsForValuesAffectingTypeHasChanged;
+ (id)keyPathsForValuesAffectingType;
+ (id)kvoChildPathForValuePath:(id)arg1;
@property(retain, nonatomic) DBGLazyObservableDictionary *lazyChildValuesByName; // @synthesize lazyChildValuesByName=_lazyChildValuesByName;
@property(retain) DBGDataValueSummaryFormatter *summaryFormatter; // @synthesize summaryFormatter=_summaryFormatter;
@property BOOL containsFunctionExpressions; // @synthesize containsFunctionExpressions=_containsFunctionExpressions;
@property int valueValidity; // @synthesize valueValidity=_valueValidity;
@property(readonly) DBGDataType *dynamicType; // @synthesize dynamicType=_dynamicType;
@property(readonly) DBGStackFrame *stackFrame; // @synthesize stackFrame=_stackFrame;
- (id)_contentDescription;
- (id)_contentDescriptionWithChildValuesAtLevel:(unsigned long long)arg1;
- (id)description;
- (id)_paddingForLevel:(unsigned long long)arg1;
- (void)_handleChildValuesChanged;
- (id)valueForKey:(id)arg1 forLazyDictionary:(id)arg2;
- (id)_childWithName:(id)arg1;
- (void)watch;
@property(readonly) NSString *realName;
@property(readonly) BOOL childValuesCountValid;
@property(readonly) NSArray *childValues;
@property(readonly) BOOL hasChildValues;
@property(readonly) BOOL inScope;
- (void)_updateSummaryFormatterIfNecessary;
- (void)_updateSummaryFormatter;
- (BOOL)wantsToProvideSummary;
- (id)_attributedStringByEscapeNewlines:(id)arg1;
@property(readonly) NSAttributedString *primitiveFormattedSummary;
@property(readonly) NSAttributedString *formattedSummary;
- (void)_summaryFormatterInvalidated:(id)arg1;
@property(readonly) BOOL typeHasChanged;
@property(readonly) NSString *type;
@property(readonly) BOOL valueHasChanged;
@property(readonly) BOOL isValueEditable;
@property(copy) NSString *value;
@property(readonly) NSString *name;
@property(readonly) DBGDataValue *parent;
@property(readonly) BOOL dynamicTypeHasChanged;
@property(readonly) BOOL summaryHasChanged;
@property(retain) DBGDataValueFormat *format;
@property(readonly) NSString *blockStartAddress;
@property(readonly) NSString *summary;
- (void)primitiveSetDynamicType:(id)arg1;
- (void)setDynamicType:(id)arg1;
@property(readonly) DBGDataType *staticType;
@property(readonly) NSString *expressionPath;
@property(readonly) NSMutableSet *requestedChildrenByName; // @synthesize requestedChildrenByName=_requestedChildrenByName;
- (id)initWithStackFrame:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly) BOOL treatSummaryAsValue;

@end

@interface DBGDataType : NSObject
{
    NSString *_typeName;
    NSString *_typeNameWithoutQualifiers;
}

+ (BOOL)isZombie:(id)arg1;
@property(readonly) NSString *typeName; // @synthesize typeName=_typeName;
- (id)description;
@property(readonly) NSString *typeNameWithoutQualifiers;
@property(readonly) BOOL isBOOLOrBoolean;
@property(readonly) BOOL isUnknownType;
@property(readonly) BOOL isPointer;
- (id)initWithTypename:(id)arg1;

@end

@interface DBGStackFramesDefaultCompressionStrategy : NSObject <IDEDebugCompressionStrategy>
{
}

+ (id)genericMaskFilePathWithColorsInRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
+ (id)maskFilePathForUserCodeWithColorsInRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
+ (id)maskFilePathForModulePathString:(id)arg1 withColorsInRed:(double *)arg2 green:(double *)arg3 blue:(double *)arg4 alpha:(double *)arg5;
+ (id)_filePathForBlock:(id)arg1 withColorsInRed:(void)arg2 green:(double *)arg3 blue:(double *)arg4 alpha:(double *)arg5;
+ (id)sharedInstance;
- (id)compressStackFrames:(id)arg1 level:(unsigned long long)arg2;
- (unsigned long long)defaultCompressionLevel;
- (unsigned long long)maxCompressionLevel;
- (id)_initInternal;
- (id)init;

@end

@interface DBGCodeModule : NSObject
{
    DVTFilePath *_filePath;
    NSString *_name;
    NSNumber *_timestamp;
}

+ (id)logAspect;
+ (id)keyPathsForValuesAffectingTimestamp;
+ (id)keyPathsForValuesAffectingName;
@property(readonly) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(readonly) NSNumber *timestamp;
@property(readonly) NSString *name; // @synthesize name=_name;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithPathString:(id)arg1;

@end

@interface DBGDataValueSummaryFormatter : NSObject
{
    DBGDataValue *_dataValue;
    DBGDataValueSummaryFormat *_format;
    NSAttributedString *_attributedSummaryValue;
    BOOL _containsFunctionExpressions;
    unsigned long long _numDependentValues;
    unsigned long long _numDependentExpressions;
    NSMutableDictionary *_cachedPathValues;
    NSMutableDictionary *_cachedExpressionValues;
}

@property(retain) NSAttributedString *attributedSummaryValue; // @synthesize attributedSummaryValue=_attributedSummaryValue;
@property(readonly) DBGDataValueSummaryFormat *format; // @synthesize format=_format;
@property(readonly) NSString *formatString;
- (void)_updateAttributedSummaryValueIfPossible;
- (void)_updateAttributedSummaryValueToNotAvailable;
- (void)_doObserveExpressionParts;
- (void)_observeExpressionParts;
- (void)_observeValuePathParts;
- (id)initFormatterForDataValue:(id)arg1 withFormat:(id)arg2;

@end

@interface DBGSummaryPart : NSObject
{
    NSString *_wholeString;
    struct _NSRange _partRange;
    struct _NSRange _contentRange;
    NSArray *_children;
    NSArray *_valuePathParts;
    NSArray *_expressionParts;
}

+ (BOOL)_containsKnownInvalidStrings:(id)arg1;
+ (id)formatterForString:(id)arg1;
+ (id)changedPropertyPathForField:(int)arg1;
+ (id)propertyPathForField:(int)arg1;
+ (int)dataFieldForString:(id)arg1;
@property(readonly) NSArray *children; // @synthesize children=_children;
@property(readonly) NSString *wholeString; // @synthesize wholeString=_wholeString;
@property(readonly) struct _NSRange contentRange; // @synthesize contentRange=_contentRange;
@property(readonly) struct _NSRange partRange; // @synthesize partRange=_partRange;
@property(readonly) BOOL requiresExpressionPath;
@property(readonly) NSArray *expressionParts;
@property(readonly) NSArray *valuePathParts;
- (id)stringForValuePaths:(id)arg1 expressionValues:(id)arg2 andDataValue:(id)arg3;
@property(readonly) NSString *contentString;
@property(readonly) NSString *partString;
- (BOOL)_parse;
- (id)description;
- (id)_initWithString:(id)arg1 partRange:(struct _NSRange)arg2 andContentRange:(struct _NSRange)arg3;

@end

@interface DBGSummaryExpressionPart : DBGSummaryPart
{
    int _field;
}

@property(readonly) NSString *valueWasChangedKeyPath;
@property(readonly) NSString *valueKeyPath;
- (id)expressionParts;
- (id)valuePathParts;
- (id)stringForValuePaths:(id)arg1 expressionValues:(id)arg2 andDataValue:(id)arg3;
- (id)expressionStringWithDataValue:(id)arg1;
- (id)_initWithString:(id)arg1 withStartAt:(unsigned long long)arg2 length:(unsigned long long)arg3;

@end

@interface DBGSummaryValuePathPart : DBGSummaryPart
{
    int _field;
}

@property(readonly) NSString *valueWasChangedKeyPath;
@property(readonly) NSString *valueKeyPath;
- (id)expressionParts;
- (id)valuePathParts;
- (id)stringForValuePaths:(id)arg1 expressionValues:(id)arg2 andDataValue:(id)arg3;
- (BOOL)_parse;
- (id)_initWithString:(id)arg1 withStartAt:(unsigned long long)arg2 length:(unsigned long long)arg3;

@end

@interface DBGSummaryPlaceholderPart : DBGSummaryPart
{
    int _type;
}

- (BOOL)requiresExpressionPath;
- (id)stringForValuePaths:(id)arg1 expressionValues:(id)arg2 andDataValue:(id)arg3;
- (id)_initWithString:(id)arg1 withStartAt:(unsigned long long)arg2 length:(unsigned long long)arg3;

@end

@interface DBGDataValueSummaryFormatManager : NSObject
{
    DVTMapTable *_sessionSpecificData;
    NSMutableDictionary *_summaryFormatsByType;
    NSMutableDictionary *_userDefinedFormatters;
    BOOL _hasUnhandledArchiveData;
}

+ (id)summaryFormatterDirectories;
+ (id)legacyCustomDataFormattersPath;
+ (id)sharedManager;
- (void)_writeUserDefinedFormatters;
- (void)_loadUserDefinedFormatters;
- (void)addSummaryFormatters:(id)arg1 fromXMLUnarchiver:(id)arg2;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)arg1;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1;
- (void)setSummaryFormat:(id)arg1 forType:(id)arg2;
- (id)_defaultSummaryFormatForType:(id)arg1;
- (id)summaryFormatForType:(id)arg1;
- (id)summaryFormatForDataValue:(id)arg1;
- (id)_sessionSpecficInfo:(id)arg1;
- (id)summaryFormatsByType;
- (id)loadDataFormattersFromDirectory:(id)arg1;
- (id)init;

@end

@interface DBGDataValueSummaryFormat : NSObject
{
    NSString *_formatString;
    NSString *_type;
    DBGSummaryPart *_formatRoot;
    DVTFilePath *_dylibPath;
    BOOL _userDefined;
}

+ (id)zombieFormatForType:(id)arg1;
+ (BOOL)writeSummaryFormats:(id)arg1 toPath:(id)arg2;
+ (id)legacySummaryFormatsAtPath:(id)arg1;
@property BOOL userDefined; // @synthesize userDefined=_userDefined;
@property(readonly) DVTFilePath *dylibPath; // @synthesize dylibPath=_dylibPath;
@property(readonly) NSString *type; // @synthesize type=_type;
@property(readonly) NSString *formatString; // @synthesize formatString=_formatString;
@property(readonly) DBGSummaryPart *formatRoot; // @synthesize formatRoot=_formatRoot;
- (void)dvt_encodeRelationshipsWithXMLArchiver:(id)arg1;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1;
- (void)setType:(id)arg1;
- (void)setFormatString:(id)arg1;
- (id)init;
- (id)initFromXMLUnarchiver:(id)arg1 archiveVersion:(float)arg2;
- (id)initWithString:(id)arg1 forType:(id)arg2 usingDylibPath:(id)arg3;

@end

@interface DBGLazyObservableDictionary : NSMutableDictionary
{
    NSMutableDictionary *_backingDictionary;
    id <DBGLazyObservableDictionaryDelegate> _delegate;
}

@property(readonly) id <DBGLazyObservableDictionaryDelegate> delegate; // @synthesize delegate=_delegate;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)keyEnumerator;
- (id)objectForKey:(id)arg1;
- (id)valueForKeyPath:(id)arg1;
- (unsigned long long)count;
- (BOOL)hasObjectForKey:(id)arg1;
- (id)initWithDelegate:(id)arg1;

@end

@interface DBGMemoryData : NSObject <IDEDebugNavigableModel>
{
    NSString *_expression;
    unsigned long long _startingAddress;
    unsigned long long _numberOfBytes;
    NSData *_rawMemoryData;
    BOOL _shouldAutoUpdate;
    DBGProcess *_parentProcess;
    NSString *_uuid;
    NSURL *_url;
}

@property(readonly) NSURL *url; // @synthesize url=_url;
@property(readonly) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain) DBGProcess *parentProcess; // @synthesize parentProcess=_parentProcess;
@property BOOL shouldAutoUpdate; // @synthesize shouldAutoUpdate=_shouldAutoUpdate;
@property(copy) NSData *rawMemoryData; // @synthesize rawMemoryData=_rawMemoryData;
@property unsigned long long numberOfBytes; // @synthesize numberOfBytes=_numberOfBytes;
@property unsigned long long startingAddress; // @synthesize startingAddress=_startingAddress;
@property(copy) NSString *expression; // @synthesize expression=_expression;
- (void)_updateUsingExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2;
- (void)updateNumberOfBytes:(unsigned long long)arg1;
- (void)updateUsingExpression:(id)arg1;
- (void)update;
- (void)autoUpdate;
@property(readonly) IDELaunchSession *launchSession;
@property(readonly) NSString *associatedProcessUUID;
- (id)initWithExpression:(id)arg1 numberOfBytes:(unsigned long long)arg2 process:(id)arg3;

@end

@interface DBGMemoryDataURLParts : NSObject
{
    int _processID;
    NSString *_memoryDataUUID;
}

+ (id)urlParts:(id)arg1;
+ (BOOL)isMemoryDataURL:(id)arg1;
@property(readonly) NSString *memoryDataUUID; // @synthesize memoryDataUUID=_memoryDataUUID;
@property(readonly) int processID; // @synthesize processID=_processID;
- (id)_initWithProcessID:(int)arg1 memoryDataUUID:(id)arg2;

@end

@interface _DBGDebuggerFoundationPrivateClassForFindingBundle : NSObject
{
}

@end

@interface DBGThreadStateInterpreter : NSObject
{
}

+ (BOOL)_doesStackFrameAtIndex:(unsigned long long)arg1 inStackFrames:(id)arg2 matchName:(id)arg3;
+ (BOOL)_doAnyOfTheFirst:(unsigned long long)arg1 stackFrames:(id)arg2 matchName:(id)arg3;
+ (BOOL)_isThreadInConditionalWait:(id)arg1;
+ (BOOL)_isThreadWaitingForLock:(id)arg1;
+ (BOOL)_isThreadWaitingForSpinLock:(id)arg1;
+ (void)updateStateOfThread:(id)arg1 usingStackFrames:(id)arg2;
+ (BOOL)useThreadStateInterpreter;

@end

@interface DBGDataValueFormat : NSObject
{
    NSString *_displayName;
    unsigned long long _tag;
}

+ (id)binaryFormatUsingTag:(unsigned long long)arg1;
+ (id)osTypeFormatUsingTag:(unsigned long long)arg1;
+ (id)octalFormatUsingTag:(unsigned long long)arg1;
+ (id)unsignedDecimalFormatUsingTag:(unsigned long long)arg1;
+ (id)decimalFormatUsingTag:(unsigned long long)arg1;
+ (id)hexFormatUsingTag:(unsigned long long)arg1;
+ (id)naturalFormatUsingTag:(unsigned long long)arg1;
@property(readonly) unsigned long long tag; // @synthesize tag=_tag;
@property(readonly) NSString *displayName; // @synthesize displayName=_displayName;
- (id)initWithDisplayName:(id)arg1 tag:(unsigned long long)arg2;

@end

@interface DBGSignal : NSObject
{
    unsigned long long _number;
    NSString *_name;
    NSString *_description;
    BOOL _isFatal;
}

+ (id)signals;
+ (BOOL)isSignalNumberFatal:(unsigned long long)arg1;
+ (BOOL)isSignalFatal:(id)arg1;
@property(readonly) BOOL isFatal; // @synthesize isFatal=_isFatal;
@property(readonly) NSString *description; // @synthesize description=_description;
@property(readonly) NSString *name; // @synthesize name=_name;
@property(readonly) unsigned long long number; // @synthesize number=_number;
- (id)_initWithNumber:(unsigned long long)arg1 name:(id)arg2 description:(id)arg3 isFatal:(BOOL)arg4;

@end

@interface DBGDisassemblyInstructionList : NSObject
{
    NSString *_disassemblyAsString;
}

@property(readonly) NSString *disassemblyAsString; // @synthesize disassemblyAsString=_disassemblyAsString;
- (id)initWithDisassembly:(id)arg1;

@end

@interface DBGCompressionInfoProvider : NSObject
{
    id _debugInfoForIndexQueryBlock;
    id _libraryNameForIndexQueryBlock;
}

@property(readonly) id libraryNameForIndexQueryBlock; // @synthesize libraryNameForIndexQueryBlock=_libraryNameForIndexQueryBlock;
@property(readonly) id debugInfoForIndexQueryBlock; // @synthesize debugInfoForIndexQueryBlock=_debugInfoForIndexQueryBlock;
- (id)initWithDebugInfoQueryBlock:(id)arg1 libraryNameQueryBlock:(void)arg2;

@end

@interface DBGPerformanceMetrics : NSObject
{
    DVTPerformanceMetric *_perceivedStepMetric;
    DVTPerformanceMetric *_variablesViewUpdateMetric;
    DVTPerformanceMetric *_nonPrimaryPCUpdateMetric;
}

+ (id)defaultMetrics;
- (void)disassemblyFetchCompleted:(id)arg1;
- (void)disassemblyFetchStarted:(id)arg1;
- (void)formattedSummaryFetchCompleted:(id)arg1;
- (void)formattedSummaryFetchStarted:(id)arg1;
- (void)nonPrimaryPCUpdateCompleted;
- (void)nonPrimaryPCUpdateStarted;
- (void)stackFrameFetchCompleted:(id)arg1;
- (void)stackFrameFetchStarted:(id)arg1;
- (void)variablesViewUpdateCompleted;
- (void)variablesViewUpdateStarted;
- (void)perceivedStepCompleted;
- (void)perceivedStepStarted;

@end

