/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/GPUDebuggerKit.ideplugin/Contents/MacOS/GPUDebuggerKit
 * UUID: 660E4DEC-8805-3447-A3B8-7FEF19D09CF4
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol IDEDebugCompressionStrategy <NSObject>
+ (id)genericMaskFilePathWithColorsInRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
+ (id)maskFilePathForUserCodeWithColorsInRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
+ (id)maskFilePathForModulePathString:(id)arg1 withColorsInRed:(double *)arg2 green:(double *)arg3 blue:(double *)arg4 alpha:(double *)arg5;
- (id)compressStackFrames:(id)arg1 level:(unsigned long long)arg2;
@end

@protocol IDEDebugNavigableModel <NSObject>
@property(readonly) IDELaunchSession *launchSession;
@property(readonly) NSString *associatedProcessUUID;
@end

@protocol IDEGeniusResultNavigableRepresentedObject <NSObject>
- (id)geniusResult_identifierForGeniusCategory;
- (id)geniusResult_identifierForManualCategory;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end

@interface GPUTraceGroupNavigableItem : IDEKeyDrivenNavigableItem
{
    BOOL _showOnlyInterestingTrace;
    NSMutableArray *_cachedChildRepresentedObjects;
}

@property BOOL showOnlyInterestingTrace; // @synthesize showOnlyInterestingTrace=_showOnlyInterestingTrace;
- (void)invalidateChildItems;
- (id)childRepresentedObjects;
- (void)_filterGroup:(id)arg1;
- (id)subtitle;
- (id)initWithRepresentedObject:(id)arg1;

@end

@interface GPUScrubberInfo : NSObject
{
    IDEWorkspaceTabController *_tabController;
    unsigned long long _drawLocation;
    id _sender;
    int _direction;
}

@property(readonly) int direction; // @synthesize direction=_direction;
@property(readonly) id sender; // @synthesize sender=_sender;
@property(readonly) unsigned long long drawLocation; // @synthesize drawLocation=_drawLocation;
@property(readonly) IDEWorkspaceTabController *tabController; // @synthesize tabController=_tabController;
- (id)initWithSender:(id)arg1 workspaceTabController:(id)arg2 drawLocation:(unsigned long long)arg3 direction:(int)arg4;

@end

@interface GPUTraceAPINavigableItem : IDEKeyDrivenNavigableItem
{
    long long _compressionValue;
    long long _maxCompressionValue;
    NSArray *_cachedChildRepresentedObjects;
    NSIndexSet *_lastCompressedIndexSet;
}

- (BOOL)setCompressionValue:(long long)arg1 maxCompressionValue:(long long)arg2;
- (void)invalidateChildItems;
- (id)childRepresentedObjects;
- (id)initWithRepresentedObject:(id)arg1;

@end

@interface GPUCompressedStackFrameNavigableItem : IDEKeyDrivenNavigableItem
{
}

- (id)initWithStackFrames:(id)arg1 parent:(id)arg2;

@end

@interface GPUCompressedStackFrame : NSObject <IDEDebugNavigableModel>
{
    NSArray *_representedStackFrames;
}

@property(readonly) NSArray *representedStackFrames; // @synthesize representedStackFrames=_representedStackFrames;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly) IDELaunchSession *launchSession;
@property(readonly) NSString *associatedProcessUUID;
- (BOOL)isGroupHeader:(id)arg1;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_name;
@property(readonly) NSNumber *frameNumber;
- (id)initWithStackFrames:(id)arg1;

@end

// Not exported
@interface GPUCompressionInfoProvider : NSObject
{
    id _debugInfoForIndexQueryBlock;
    id _libraryNameForIndexQueryBlock;
}

@property(readonly) id libraryNameForIndexQueryBlock; // @synthesize libraryNameForIndexQueryBlock=_libraryNameForIndexQueryBlock;
@property(readonly) id debugInfoForIndexQueryBlock; // @synthesize debugInfoForIndexQueryBlock=_debugInfoForIndexQueryBlock;
- (id)initWithDebugInfoQueryBlock:(id)arg1 libraryNameQueryBlock:(void)arg2;

@end

// Not exported
@interface GPUStackFramesDefaultCompressionStrategy : NSObject <IDEDebugCompressionStrategy>
{
}

+ (id)genericMaskFilePathWithColorsInRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
+ (id)maskFilePathForUserCodeWithColorsInRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
+ (id)maskFilePathForModulePathString:(id)arg1 withColorsInRed:(double *)arg2 green:(double *)arg3 blue:(double *)arg4 alpha:(double *)arg5;
+ (id)_filePathForBlock:(id)arg1 withColorsInRed:(void)arg2 green:(double *)arg3 blue:(double *)arg4 alpha:(double *)arg5;
+ (id)sharedInstance;
- (id)compressStackFrames:(id)arg1 level:(unsigned long long)arg2;
- (unsigned long long)defaultCompressionLevel;
- (unsigned long long)maxCompressionLevel;
- (id)initInternal;
- (id)init;

@end

@interface GPUNavigatorCompressedDataCell : DVTImageAndTextCell
{
    NSColor *_color;
}

+ (id)sharedInstance;
@property(copy) NSColor *color; // @synthesize color=_color;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (void)_ide_commonInit;

@end

@interface GPUStackFrameNavigableItem : IDEFileNavigableItem
{
}

- (id)contentDocumentLocation;
- (id)name;
- (id)documentType;
- (id)newImage;
- (id)fileURL;
- (id)_stackFrame;

@end

@interface GPUTraceOutlineDomainProvider : IDENavigableItemDomainProvider
{
}

+ (id)navigableItemImageForDocumentURL:(id)arg1;
+ (id)navigableItemNameForDocumentURL:(id)arg1;
+ (id)domainObjectForWorkspace:(id)arg1;

@end

@interface GPUSharedUIState : NSObject
{
    struct dispatch_queue_s *_queue;
    NSString *_identifier;
    DVTMapTable *_stateTable;
}

@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
- (void)setState:(id)arg1 ForKey:(id)arg2;
- (id)stateForKey:(id)arg1;
- (void)dealloc;
- (id)initWithIdentifer:(id)arg1;

@end

@interface GPUSharedEditorUIState : GPUSharedUIState
{
}

@end

@interface GPUSharedTabUIState : GPUSharedUIState
{
    IDEEditorDocument *_currentTraceDocument;
    GPUTraceSession *_currentTraceSession;
    GPUTraceDocumentLocation *_currentMainEditorLocation;
    BOOL _loadingNewResources;
}

@property(readonly) BOOL loadingNewResources; // @synthesize loadingNewResources=_loadingNewResources;
@property(retain) GPUTraceDocumentLocation *currentMainEditorLocation; // @synthesize currentMainEditorLocation=_currentMainEditorLocation;
@property __weak GPUTraceSession *currentTraceSession; // @synthesize currentTraceSession=_currentTraceSession;
@property BOOL currentLocationIsDrawItem; // @dynamic currentLocationIsDrawItem;
- (id)currentStateMirror;
- (id)currentMainEditorItem;

@end

@interface GPUSharedWorkspaceUIState : GPUSharedUIState
{
}

@end

@interface GPUSharedUIStateManager : NSObject
{
    struct dispatch_queue_s *_queue;
    DVTMapTable *_sharedStateMapTable;
}

+ (id)sharedUIStateManager;
- (id)sharedStateForEditor:(id)arg1;
- (id)sharedStateForWorkspaceTabController:(id)arg1;
- (id)sharedStateForWorkspace:(id)arg1;
- (void)dealloc;
- (id)_init;
- (id)init;

@end

@interface GPUTraceSession (GPUTraceSessionNavigableItemPropertySupport)
@property(readonly) NSArray *navigableTraceGroupItems;
@end

@interface GPUTraceProcessItem (GPUTraceOutlineItemNavigableItemPropertySupport)
- (id)navigableItem_image;
@end

@interface GPUTraceOutlineItem (GPUTraceOutlineItemNavigableItemPropertySupport)
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) DVTFileDataType *navigableItem_documentType;
- (id)ideModelObjectTypeIdentifier;
@end

@interface GPUTraceAPIItem (GPUTraceOutlineItemNavigableItemPropertySupport)
@property(readonly) NSString *navigableItem_name;
@end

@interface GPUTraceResources (GPUTraceOutlineItemNavigableItemPropertySupport)
- (id)gputraceResources_children;
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_name;
- (id)navigableItem_image;
- (id)navigableItem_documentType;
- (id)ideModelObjectTypeIdentifier;
@end

@interface GPUTraceResourceItem (GPUTraceOutlineItemNavigableItemPropertySupport)
- (id)navigableItem_contentDocumentLocation;
- (id)navigableItem_name;
- (id)navigableItem_image;
- (id)navigableItem_documentType;
- (id)ideModelObjectTypeIdentifier;
@end

@interface GPUTraceDocumentLocation (GPUTraceDocumentLocationNavigableItemSupport) <IDEGeniusResultNavigableRepresentedObject>
- (id)geniusResult_identifierForGeniusCategory;
- (id)geniusResult_identifierForManualCategory;
@end

@interface DYStackFrame (GPUTraceOutlineItemNavigableItemPropertySupport)
- (id)contentDelegateUIExtensionIdentifier;
- (id)associatedProcessUUID;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSImage *navigableItem_image;
- (id)gpudebugger_createImageFromFilePath:(id)arg1 withRed:(float)arg2 green:(float)arg3 blue:(float)arg4 alpha:(float)arg5;
- (id)gpudebugger_uti;
- (id)gpudebugger_sourceURL;
@end

