/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDEAppleScriptCore.ideplugin/Contents/MacOS/IDEAppleScriptCore
 * UUID: 7C879A54-1564-3735-A657-9F3C60943EFB
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 2052.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface IDEAppleScriptIndexQueryProvider : IDEIndexGenericQueryProvider
{
}

@end

@interface IDEAppleScriptIndexDataSource : IDEIndexDataSource
{
}

+ (id)dataSourceVersion;
- (BOOL)generateDataForJob:(id)arg1;
- (void)processContents:(id)arg1 forFile:(id)arg2 index:(id)arg3;

@end

