/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDEAppleScriptEditor.ideplugin/Contents/MacOS/IDEAppleScriptEditor
 * UUID: 5769E6F3-7708-3EC2-9222-074FE3781439
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1165.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@interface IDEAppleScriptDocument : IDESourceCodeDocument
{
}

- (long long)nodeTypeForItem:(id)arg1 withContext:(id)arg2;

@end

