/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDEAppleScriptEditor.ideplugin/Contents/MacOS/IDEAppleScriptEditor
 * UUID: 25129102-ED50-3B19-B894-2A35AE36341C
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 2052.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface IDEAppleScriptDocument : IDESourceCodeDocument
{
}

- (long long)nodeTypeForItem:(id)arg1 withContext:(id)arg2;

@end

