/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDEGit.ideplugin/Contents/MacOS/IDEGit
 * UUID: 0E51BEDA-4000-3D07-B0DB-38CA56F427AC
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1169.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol IDESourceControlProtocol <NSObject>
- (id)operationForRequest:(id)arg1;
- (BOOL)authenticationRequiredForRequest:(id)arg1;
- (BOOL)validateRequest:(id)arg1 error:(id *)arg2;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end

@interface GitController : NSObject <IDESourceControlProtocol>
{
}

- (id)operationForRequest:(id)arg1;
- (BOOL)authenticationRequiredForRequest:(id)arg1;
- (BOOL)validateRequest:(id)arg1 error:(id *)arg2;

@end

@interface GitOperation : IDESourceControlTaskOperation
{
}

+ (void)parseForStatusAndPathWithLine:(id)arg1 withFullPath:(id)arg2 puttingIntoDictionary:(id)arg3;
- (id)errorFromErrorMessage:(id)arg1;
- (id)defaultArguments;
- (id)launchPath;
- (id)initWithRequest:(id)arg1;

@end

@interface GitCreateRepositoryOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitCloneOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitCheckoutOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitListOperation : IDESourceControlOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitListFilesOperation : GitOperation
{
}

- (void)parseData;
- (id)launchPath;
- (id)initWithRequest:(id)arg1;

@end

@interface GitLogOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;
- (id)_prettyFormatWithArray:(id)arg1;

@end

@interface GitExportTreeOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitFetchOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitAddOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitBlameOperation : GitOperation
{
    NSDateFormatter *_formatter;
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitBranchOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitCommitOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitCurrentBranchOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitIgnoreOperation : IDESourceControlOperation
{
}

@end

@interface GitListRemotesOperation : IDESourceControlOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitListStandardRemotesOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitListRemoteBranchesOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitTrackingBranchNameOperation : IDESourceControlOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitRemoteRefForBranchOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitMergeBranchForBranchOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitAddRemoteOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitRemoveRemoteOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitTrackRemoteBranchOperation : GitOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitInfoOperation : IDESourceControlOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitMergeBaseOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitListSVNRemoteOperation : GitOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitFetchRemoteOriginOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitFetchSVNRemoteOriginOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitFetchSVNRemoteNameOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitMergeOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitRemoveOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitStatusOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitUpdateOperation : IDESourceControlOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitDiffOperation : GitOperation
{
    BOOL _diffNameAndStatusOnly;
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitSvnFetchOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitSvnRebaseOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface GitPullOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitPushOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitTarOperation : IDESourceControlTaskOperation
{
}

- (void)parseData;
- (id)launchPath;
- (id)initWithRequest:(id)arg1;

@end

@interface GitExportFileOperation : GitOperation
{
    IDESourceControlTaskOperation *_pipeToOperation;
}

- (id)initWithRequest:(id)arg1;
- (id)pipeToOperation;

@end

@interface GitListBranchesOperation : GitOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface GitCopyOperation : IDESourceControlOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitMakeDirectoryOperation : IDESourceControlOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface GitMoveOperation : GitOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface NSString (IDEGit)
- (int)idegit_sourceControlStatus;
@end

@interface NSData (GitUtilities)
- (id)git_componentsSeparatedByNULLTerminator;
@end

