/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDEInstrumentsService.ideplugin/Contents/MacOS/IDEInstrumentsService
 * UUID: 9147A59F-3DDA-32F5-B946-6FB4C18C4085
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 2083.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 *       Run path: @loader_path/../../../
 *               = /Applications/Xcode.app/Contents/PlugIns
 */

@protocol IDEAnalysisToolService <NSObject>
@property(retain) IDEAnalysisTool *currentTool;
- (void)setSelectedToolIdentifier:(id)arg1 forPlatformIdentifier:(id)arg2;
- (id)analysisToolsForPlatform:(id)arg1;
- (id)operationWithCommandLineArgs:(id)arg1 environmentVariables:(id)arg2 workingDirectory:(id)arg3 workspaceFilePath:(id)arg4 projectFilePath:(id)arg5 outError:(id *)arg6;
- (void)setRunDestination:(id)arg1;
- (void)setBuildProductsPath:(id)arg1;
- (void)setLocation:(id)arg1;
- (id)initWithRunnableUTIType:(id)arg1;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@optional
- (id)debugDescription;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface XRXcodeAnalysisService : NSObject <IDEAnalysisToolService>
{
    DVTFileDataType *_runnableUTIType;
    id _runnableLocation;
    DVTFilePath *_runnableBuildProductPath;
    IDERunDestination *_runDestination;
    IDEAnalysisTool *_currentTool;
    NSMutableDictionary *_currentToolForPlatformDict;
    NSDictionary *_platformToAnalysisToolsMap;
}

+ (id)_apppleInternalTemplatesPath;
+ (id)_homePrefsTemplatesPath;
+ (id)_instrumentsAppTemplatesPath;
+ (id)_platformsPath;
+ (id)_developerAppsPath;
+ (id)_analysisToolsForPlugin:(id)arg1 platform:(id)arg2;
+ (id)_analysisToolsForPlatform:(id)arg1;
+ (id)_analysisToolsDictForAllPlatforms;
+ (id)_analysisToolsAtPath:(id)arg1 type:(int)arg2;
+ (id)sharedPlatformToAnalysisToolsMap;
+ (id)_sharedGraphicsDetectiveTool;
+ (id)_anyPlatformID;
+ (id)_graphicsPerformanceDetectivePath;
+ (void)addUniqueTools:(id)arg1 toArray:(id)arg2;
- (void)setRunDestination:(id)arg1;
- (void)setBuildProductsPath:(id)arg1;
- (void)setLocation:(id)arg1;
- (id)operationWithCommandLineArgs:(id)arg1 environmentVariables:(id)arg2 workingDirectory:(id)arg3 workspaceFilePath:(id)arg4 projectFilePath:(id)arg5 outError:(id *)arg6;
- (void)_launch:(id)arg1 WithConfigFile:(id)arg2;
- (id)_analysisAppPathForType:(int)arg1;
- (id)_instrumentsPath;
- (void)setSelectedToolIdentifier:(id)arg1 forPlatformIdentifier:(id)arg2;
- (id)currentToolForPlatformIdentifier:(id)arg1;
- (id)validToolForToolIdentifier:(id)arg1 platformIndentifier:(id)arg2;
@property(retain) IDEAnalysisTool *currentTool; // @synthesize currentTool=_currentTool;
- (id)_currentToolForPlatformDict;
- (id)_currentPlatformIdentifier;
- (id)analysisToolsForPlatform:(id)arg1;
- (id)initWithRunnableUTIType:(id)arg1;

@end

