/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDEIssueNavigator.ideplugin/Contents/MacOS/IDEIssueNavigator
 * UUID: BE646AAB-EDAF-30D6-AE3C-C767EF359029
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 2053.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface IDEIssueNavigator : IDENavigator
{
    IDENavigatorOutlineView *_outlineView;
    DVTScopeBarView *_scopeBarView;
    NSButton *_scopeByFileButton;
    NSButton *_scopeByTypeButton;
    NSArray *_selectedNavigables;
    IDENavigatorDataCell *_groupCell;
    IDENavigatorDataCell *_subGroupCell;
    IDENavigatorDataCell *_issueCell;
    IDENavigatorDataCell *_subissueCell;
    NSMutableSet *_collapsedGroups;
    NSMutableSet *_collapsedFiles;
    NSMutableSet *_collapsedTypes;
    NSMutableSet *_expandedIssues;
    NSSet *_collapsedGroupsBeforeFiltering;
    NSSet *_collapsedFilesBeforeFiltering;
    NSSet *_collapsedTypesBeforeFiltering;
    NSSet *_expandedIssuesBeforeFiltering;
    NSMutableArray *_autoExpandItems;
    double _currentModifiedExpansionTimestamp;
    NSString *_filterPatternString;
    NSMutableArray *_stateChangeObservingTokens;
    id <DVTObservingToken> _selectedNavigablesObservingToken;
    id <DVTObservingToken> _activeSchemeObservingToken;
    id <DVTObservingToken> _activeRunDestinationObservingToken;
    id <DVTObservingToken> _implicitDependenciesObservingToken;
    BOOL _showByType;
    BOOL _restoringState;
    BOOL _autoExpanding;
    BOOL _errorFilteringEnabled;
    BOOL _recentFilteringEnabled;
    BOOL _clearingFilterPredicate;
    BOOL _hasScheduledAutoExpansion;
}

+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
@property(copy, nonatomic) NSSet *expandedIssues; // @synthesize expandedIssues=_expandedIssues;
@property(copy, nonatomic) NSSet *collapsedTypes; // @synthesize collapsedTypes=_collapsedTypes;
@property(copy, nonatomic) NSSet *collapsedFiles; // @synthesize collapsedFiles=_collapsedFiles;
@property(copy, nonatomic) NSSet *collapsedGroups; // @synthesize collapsedGroups=_collapsedGroups;
@property(retain, nonatomic) NSArray *selectedNavigables; // @synthesize selectedNavigables=_selectedNavigables;
@property(nonatomic) BOOL recentFilteringEnabled; // @synthesize recentFilteringEnabled=_recentFilteringEnabled;
@property(nonatomic) BOOL errorFilteringEnabled; // @synthesize errorFilteringEnabled=_errorFilteringEnabled;
@property(copy, nonatomic) NSString *filterPatternString; // @synthesize filterPatternString=_filterPatternString;
- (void)revealNavigableItems:(id)arg1;
- (void)commitStateToDictionary:(id)arg1;
- (void)configureStateSavingObservers;
- (void)revertStateWithDictionary:(id)arg1;
- (void)clearFilterPredicate;
- (void)setFilterPredicate:(id)arg1;
- (void)_synchronizeFilteringWithOutlineView;
- (id)filterDefinitionIdentifier;
- (void)_updateFilterPredicate;
- (BOOL)_isFiltered;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (void)_autoExpandItem:(id)arg1;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (id)_subissueCell;
- (id)_issueCell;
- (id)_subGroupCell;
- (id)_groupCell;
- (id)severityStatusCellsWithRepresentedObject:(id)arg1;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (BOOL)_shouldMassExpandOrCollapseItem:(id)arg1;
- (void)_ensureNavigableItem:(id)arg1 expansionStateIsExpanded:(BOOL)arg2;
- (id)_itemsMatchingState:(id)arg1;
- (id)_leafIssueNavigableInIssuePath:(id)arg1 parentNavigable:(id)arg2 idToNavigableDict:(id)arg3;
- (id)_issueNavigableItemForIdentifierDictionary:(id)arg1 parentNavigable:(id)arg2 idToNavigableDict:(id)arg3;
- (id)_fileGroupNavigableItemForIdentifierDictionary:(id)arg1 parentNavigable:(id)arg2 idToNavigableDict:(id)arg3;
- (id)_typeGroupNavigableItemForIdentifierDictionary:(id)arg1 parentNavigable:(id)arg2 idToNavigableDict:(id)arg3;
- (id)_issueGroupNavigableItemForIdentifierDictionary:(id)arg1 idToNavigableDict:(id)arg2;
- (id)_fullIdentifierPathForNavigables:(id)arg1;
- (id)_fullIdentifierPathForNavigable:(id)arg1;
- (id)_stateIdentifierForNavigable:(id)arg1;
- (id)_stateIdentifierForIssue:(id)arg1;
- (id)_stateIdentifierForIssueTypeGroup:(id)arg1 parentNavigable:(id)arg2;
- (id)_stateIdentifierForIssueFileGroup:(id)arg1 parentNavigable:(id)arg2;
- (id)_stateIdentifierForIssueGroup:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)contextMenu_revealInLog:(id)arg1;
- (void)contextMenu_copy:(id)arg1;
- (void)copy:(id)arg1;
- (id)contextMenuSelection;
- (BOOL)_writeItems:(id)arg1 toPasteboard:(id)arg2;
- (void)contextMenu_revealInProjectNavigator:(id)arg1;
- (void)revealInProjectNavigator:(id)arg1;
- (void)_revealInProjectNavigatorUsingContextMenuSelection:(BOOL)arg1;
- (void)_pushSelection;
- (void)openDoubleClickedNavigableItemsAction:(id)arg1;
- (void)openClickedNavigableItemAction:(id)arg1;
- (void)openSelectedNavigableItemsKeyAction:(id)arg1;
- (id)openSpecifierForNavigableItem:(id)arg1 error:(id *)arg2;
- (BOOL)_canNavigateToNavigableItem:(id)arg1;
- (id)structureEditorOpenSpecifierForIssuesNavigable:(id)arg1 error:(id *)arg2;
- (id)structureEditorOpenSpecifierForLogDocumentForIssue:(id)arg1 error:(id *)arg2;
- (id)structureNavigableItemForIssuesNavigable:(id)arg1 error:(id *)arg2;
- (void)showByFile:(id)arg1;
- (void)showByType:(id)arg1;
- (id)domainIdentifier;
@property BOOL showByType;
- (BOOL)delegateFirstResponder;
- (void)primitiveInvalidate;
- (void)viewDidInstall;
- (void)loadView;

@end

@interface IDEIssueGroupNavigableItem : IDEKeyDrivenNavigableItem
{
    id <DVTObservingToken> _fileGroupsObservingToken;
    id <DVTObservingToken> _issuesWithoutFilesObservingToken;
    id <DVTObservingToken> _typeGroupsObservingToken;
}

- (id)subtitle;
- (id)keyPathsAffectingValueForSubtitle;
- (id)childRepresentedObjects;
- (void)dispose;
- (BOOL)isLeaf;
- (BOOL)isMajorGroup;

@end

@interface IDENavigableItemIssuesDomainProvider : IDENavigableItemDomainProvider
{
}

+ (id)domainObjectForWorkspace:(id)arg1;

@end

@interface IDENavigableItemWorkspaceIssueLogsDomainProvider : IDENavigableItemDomainProvider
{
}

+ (id)domainObjectForWorkspace:(id)arg1;

@end

