/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    double x;
    double y;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDEPDFViewer.ideplugin/Contents/MacOS/IDEPDFViewer
 * UUID: 3FD3C9E2-335D-3758-9FCE-FD3F964E32E0
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol DVTBasicFindBarFindable <DVTFindBarFindable>
- (BOOL)basicFindBar:(id)arg1 findPreviousByWrapping:(BOOL)arg2;
- (BOOL)basicFindBar:(id)arg1 findNextByWrapping:(BOOL)arg2;
- (long long)basicFindBar:(id)arg1 findString:(id)arg2 caseSensitive:(BOOL)arg3 withFindType:(unsigned long long)arg4 andMatchStyle:(int)arg5;
- (BOOL)basicFindBar:(id)arg1 supportsMatchStyle:(int)arg2;
- (BOOL)basicFindBar:(id)arg1 supportsFindType:(unsigned long long)arg2;

@optional
- (void)basicFindBarLostFocus:(id)arg1;
@end

@protocol DVTFindBarFindable

@optional
- (struct _NSRange)selectedRangeForFindBar:(id)arg1;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateResults:(id)arg2;
@end

@protocol IDEDocumentStructureProviding <NSObject>
@property(readonly) NSArray *ideTopLevelStructureObjects;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@optional
- (id)debugDescription;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface IDEPDFViewerDocument : IDEEditorDocument <IDEDocumentStructureProviding>
{
    PDFDocument *_pdfDocument;
}

+ (id)pdfNavigableForDocumentURL:(id)arg1 PDFOutline:(id)arg2;
+ (id)keyPathsForValuesAffectingIdeTopLevelStructureObjects;
@property(retain) PDFDocument *pdfDocument; // @synthesize pdfDocument=_pdfDocument;
@property(readonly) NSArray *ideTopLevelStructureObjects;
- (id)dataOfType:(id)arg1 error:(id *)arg2;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

@end

@interface IDEPDFViewerOutlineNavigable : NSObject
{
    NSURL *_documentURL;
    PDFDocument *_pdfDocument;
    PDFOutline *_pdfOutline;
}

@property(readonly) PDFDocument *pdfDocument; // @synthesize pdfDocument=_pdfDocument;
@property(readonly) PDFOutline *pdfOutline; // @synthesize pdfOutline=_pdfOutline;
@property(readonly) NSURL *documentURL; // @synthesize documentURL=_documentURL;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) DVTFileDataType *navigableItem_documentType;
- (id)ideModelObjectTypeIdentifier;
- (id)initWithDocumentURL:(id)arg1 PDFOutline:(id)arg2;

@end

@interface IDEPDFViewerSection : IDEPDFViewerOutlineNavigable
{
}

- (id)pdfoutline_children;

@end

@interface IDEPDFViewerPage : IDEPDFViewerOutlineNavigable
{
}

@end

@interface IDEPDFViewerDocumentLocation : DVTDocumentLocation
{
    unsigned long long _pageIndex;
    struct CGPoint _point;
}

@property(readonly) struct CGPoint point; // @synthesize point=_point;
@property(readonly) unsigned long long pageIndex; // @synthesize pageIndex=_pageIndex;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)initWithPDFDestination:(id)arg1 inPDFDocument:(id)arg2 atURL:(id)arg3;

@end

@interface IDEPDFViewerEditor : IDEEditor <DVTBasicFindBarFindable>
{
    PDFView *_pdfView;
    NSString *_findString;
    unsigned long long _findCaseSensitive;
}

+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (id)defaultViewNibBundle;
+ (id)defaultViewNibName;
@property(retain) PDFView *pdfView; // @synthesize pdfView=_pdfView;
- (void)printDocument:(id)arg1;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)pdf_zoomOut:(id)arg1;
- (void)pdf_zoomIn:(id)arg1;
- (void)pdf_previousPage:(id)arg1;
- (void)pdf_nextPage:(id)arg1;
- (void)pdf_twoPagesContinuous:(id)arg1;
- (void)pdf_twoPages:(id)arg1;
- (void)pdf_singlePageContinuous:(id)arg1;
- (void)pdf_singlePage:(id)arg1;
- (void)pdf_actualSize:(id)arg1;
- (void)pdf_automaticallyResize:(id)arg1;
- (void)basicFindBarLostFocus:(id)arg1;
- (BOOL)basicFindBar:(id)arg1 findPreviousByWrapping:(BOOL)arg2;
- (BOOL)basicFindBar:(id)arg1 findNextByWrapping:(BOOL)arg2;
- (long long)basicFindBar:(id)arg1 findString:(id)arg2 caseSensitive:(BOOL)arg3 withFindType:(unsigned long long)arg4 andMatchStyle:(int)arg5;
- (void)selectAndScrollToPDFSelection:(id)arg1;
- (BOOL)basicFindBar:(id)arg1 supportsMatchStyle:(int)arg2;
- (BOOL)basicFindBar:(id)arg1 supportsFindType:(unsigned long long)arg2;
- (id)createFindBar;
- (BOOL)findBarSupported;
- (void)useSelectionForReplace:(id)arg1;
- (void)useSelectionForFind:(id)arg1;
- (unsigned long long)searchOptions;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)jumpToSelection:(id)arg1;
- (void)selectDocumentLocations:(id)arg1;
- (id)currentSelectedDocumentLocations;
- (void)loadView;
- (void)takeFocus;

@end

