/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDEQuickLookEditor.ideplugin/Contents/MacOS/IDEQuickLookEditor
 * UUID: F0C98BD0-8EA0-3854-843E-93EED50E6449
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1168.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol IDEComparisonEditorDelegate <IDEEditorDelegate>

@optional
- (BOOL)comparisonEditorShouldCloseDocumentsDuringWillOpenSpecifier:(id)arg1;
- (void)comparisonEditor:(id)arg1 didReplaceAncestorDocument:(id)arg2;
- (void)comparisonEditor:(id)arg1 willReplaceAncestorDocument:(id)arg2;
- (id)comparisonEditor:(id)arg1 substituteDocumentLocationForAncestorDocumentLocation:(id)arg2;
- (void)comparisonEditor:(id)arg1 didReplaceSecondaryDocument:(id)arg2;
- (void)comparisonEditor:(id)arg1 willReplaceSecondaryDocument:(id)arg2;
- (id)comparisonEditor:(id)arg1 substituteDocumentLocationForSecondaryDocumentLocation:(id)arg2;
- (void)comparisonEditor:(id)arg1 didReplacePrimaryDocument:(id)arg2;
- (void)comparisonEditor:(id)arg1 willReplacePrimaryDocument:(id)arg2;
- (id)comparisonEditor:(id)arg1 substituteDocumentLocationForPrimaryDocumentLocation:(id)arg2;
@end

@protocol IDEComparisonEditorHostContext <NSObject>
- (BOOL)editorDocumentIsCurrentRevision;
- (BOOL)editorIsHostedInComparisonEditor;

@optional
- (BOOL)editorWantsAnnotationsFromProviderClass:(Class)arg1;
@end

@protocol IDEDocumentStructureProviding <NSObject>
@property(readonly) NSArray *ideTopLevelStructureObjects;
@end

@protocol IDEEditorDelegate <NSObject>

@optional
- (id)scopeBarsManagerForEditor:(id)arg1;
@end

@protocol IDENavigableItemFileReferenceProxy <NSObject>
@property(readonly) IDENavigableItem *primaryChildItem;

@optional
- (BOOL)showSubitems;
@end

@protocol NSCoding
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end

@protocol NSSplitViewDelegate <NSObject>

@optional
- (void)splitViewDidResizeSubviews:(id)arg1;
- (void)splitViewWillResizeSubviews:(id)arg1;
- (struct CGRect)splitView:(id)arg1 additionalEffectiveRectOfDividerAtIndex:(long long)arg2;
- (struct CGRect)splitView:(id)arg1 effectiveRect:(struct CGRect)arg2 forDrawnRect:(struct CGRect)arg3 ofDividerAtIndex:(long long)arg4;
- (BOOL)splitView:(id)arg1 shouldHideDividerAtIndex:(long long)arg2;
- (BOOL)splitView:(id)arg1 shouldAdjustSizeOfSubview:(id)arg2;
- (void)splitView:(id)arg1 resizeSubviewsWithOldSize:(struct CGSize)arg2;
- (double)splitView:(id)arg1 constrainSplitPosition:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 shouldCollapseSubview:(id)arg2 forDoubleClickOnDividerAtIndex:(long long)arg3;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
@end

@protocol NSUserInterfaceValidations
- (BOOL)validateUserInterfaceItem:(id)arg1;
@end

@protocol QLPreviewViewDelegate <NSObject>

@optional
- (unsigned long long)previewView:(id)arg1 draggingSourceOperationMaskForLocal:(BOOL)arg2;
- (BOOL)previewView:(id)arg1 writePreviewItem:(id)arg2 toPasteboard:(id)arg3;
- (id)previewView:(id)arg1 namesOfPromisedFilesDroppedAtDestination:(id)arg2 forPreviewItem:(id)arg3;
- (BOOL)previewView:(id)arg1 acceptDrop:(id)arg2 onPreviewItem:(id)arg3;
- (unsigned long long)previewView:(id)arg1 validateDrop:(id)arg2 onPreviewItem:(id)arg3;
- (id)previewView:(id)arg1 customViewForPreviewItem:(id)arg2;
- (BOOL)previewView:(id)arg1 shouldPreviewItem:(id)arg2;
- (void)previewView:(id)arg1 timedOutLoadingPreviewItem:(id)arg2;
- (void)previewView:(id)arg1 didShowPreviewItem:(id)arg2;
- (void)previewView:(id)arg1 willShowPreviewItem:(id)arg2;
- (void)previewView:(id)arg1 didLoadPreviewItem:(id)arg2;
- (void)previewView:(id)arg1 willLoadPreviewItem:(id)arg2;
@end

@interface IDEQuickLookDocument : IDEEditorDocument <IDEDocumentStructureProviding>
{
    unsigned long long _numberOfPages;
}

+ (id)keyPathsForValuesAffectingIdeTopLevelStructureObjects;
@property unsigned long long numberOfPages; // @synthesize numberOfPages=_numberOfPages;
- (id)diffDataSource;
@property(readonly) NSArray *ideTopLevelStructureObjects;
- (BOOL)readFromFileWrapper:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)canSave;
- (id)objectSpecifier;

@end

@interface IDEQuickLookEditor : IDEEditor <QLPreviewViewDelegate, NSUserInterfaceValidations, IDEComparisonEditorHostContext>
{
    QLPreviewView *_qlView;
    IDEViewController *_hostViewController;
}

+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (id)defaultViewNibName;
@property __weak IDEViewController *hostViewController; // @synthesize hostViewController=_hostViewController;
@property(retain) QLPreviewView *qlView; // @synthesize qlView=_qlView;
- (BOOL)editorDocumentIsCurrentRevision;
- (BOOL)editorIsHostedInComparisonEditor;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)printDocument:(id)arg1;
- (void)runPageLayout:(id)arg1;
- (BOOL)findBarSupported;
- (void)takeFocus;
- (void)selectDocumentLocations:(id)arg1;
- (id)currentSelectedDocumentLocations;
- (void)selectPreviousContentSibling:(id)arg1;
- (void)selectNextContentSibling:(id)arg1;
- (void)pause:(id)arg1;
- (void)play:(id)arg1;
- (void)nextPage:(id)arg1;
- (void)previousPage:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)invalidate;
- (void)previewView:(id)arg1 didChangeDisplayStateForPreviewItem:(id)arg2;
- (void)previewView:(id)arg1 willShowPreviewItem:(id)arg2;
- (void)loadView;

@end

@interface IDEQuickLookLoadingView : NSView
{
}

- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface IDEQuickLookPage : NSObject
{
    NSURL *_documentURL;
    unsigned long long _pageNumber;
}

@property(readonly) unsigned long long pageNumber; // @synthesize pageNumber=_pageNumber;
@property(readonly) NSURL *documentURL; // @synthesize documentURL=_documentURL;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) DVTFileDataType *navigableItem_documentType;
- (id)ideModelObjectTypeIdentifier;
- (id)description;
- (id)initWithDocumentURL:(id)arg1 pageNumber:(unsigned long long)arg2;

@end

@interface _IDEQuickLookPrivateClassForFindingBundle : NSObject
{
}

@end

@interface IDEQuickLookDocumentLocation : DVTDocumentLocation <NSCoding>
{
    IDEQuickLookPage *_page;
}

@property(readonly) IDEQuickLookPage *page; // @synthesize page=_page;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)initWithDocumentURL:(id)arg1 page:(id)arg2;

@end

@interface IDEQuickLookInspector : IDEInspectorViewController
{
}

- (void)setContent:(id)arg1;

@end

@interface IDEQuickLookComparisonEditor : IDEComparisonEditor
{
    NSDictionary *_previouslyRestoredStateDictionary;
}

+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
- (void)find:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)restoreInternalComparisonDocumentLocationWithStateDictionary:(id)arg1;
- (void)commitStateToDictionary:(id)arg1;
- (BOOL)disableBlame;
- (void)setEditorSubmode:(int)arg1;
- (void)_updateViewBasedOnSubmode;
- (struct CGRect)overlayFrameForView:(id)arg1;
- (BOOL)pathCell:(id)arg1 shouldSeparateDisplayOfChildItemsForItem:(id)arg2;

@end

@interface IDEQuickLookVersionsLogSubmode : IDEComparisonEditorSubmode <IDEComparisonEditorDelegate>
{
    NSDictionary *_previouslyRestoredStateDictionary;
    DVTBorderedView *_primaryLayoutView;
    IDEEditor *_primaryEditor;
}

+ (id)keyPathsForValuesAffectingCurrentSelectedDocumentLocations;
+ (id)keyPathsForValuesAffectingCurrentSelectedItems;
+ (id)keyPathsForValuesAffectingKeyEditor;
@property(retain) DVTBorderedView *primaryLayoutView; // @synthesize primaryLayoutView=_primaryLayoutView;
- (void)revertComparisonEditorStateWithDictionary:(id)arg1;
- (void)commitComparisonEditorStateToDictionary:(id)arg1;
- (id)currentSelectedDocumentLocations;
- (id)currentSelectedItems;
- (void)showEmptyPrimaryEditor:(id)arg1;
- (void)hidePrimaryPlaceholder;
- (void)showPrimaryPlaceholder;
- (void)comparisonEditor:(id)arg1 didReplacePrimaryDocument:(id)arg2;
- (void)_syncStructureDocument;
- (id)_fileTextSettings;
- (void)invalidate;
- (void)viewDidInstall;
- (void)loadView;
@property(retain) IDEEditor *primaryEditor; // @synthesize primaryEditor=_primaryEditor;
@property(readonly) QLPreviewView *primaryQuickLookView;
- (id)keyEditor;

@end

@interface IDEQuickLookVersionsTwoUpSubmode : IDEComparisonEditorSubmode <IDEComparisonEditorDelegate, NSSplitViewDelegate>
{
    DVTBorderedView *_primaryLayoutView;
    DVTBorderedView *_secondaryLayoutView;
    DVTComparisonSplitView *_comparisonSplitView;
    DVTDiffSession *_diffSession;
    IDEEditor *_primaryEditor;
    IDEEditor *_secondaryEditor;
    BOOL _showingPrimaryDocumentStructure;
    id <DVTObservingToken> _selectedToken;
    id <DVTObservingToken> _responderToken;
    id <DVTObservingToken> _statsObservationToken;
    id <DVTObservingToken> _conflictResolutionDidCompleteObserver;
    NSDictionary *_previouslyRestoredStateDictionary;
    IDESourceControlConflictMergeData *_previousMergeData;
    unsigned long long _documentLoadCount;
}

+ (id)logAspect;
+ (id)keyPathsForValuesAffectingCurrentSelectedDocumentLocations;
+ (id)keyPathsForValuesAffectingCurrentSelectedItems;
+ (id)keyPathsForValuesAffectingKeyEditor;
@property BOOL showingPrimaryDocumentStructure; // @synthesize showingPrimaryDocumentStructure=_showingPrimaryDocumentStructure;
@property(retain) DVTComparisonSplitView *comparisonSplitView; // @synthesize comparisonSplitView=_comparisonSplitView;
@property(retain) DVTBorderedView *secondaryLayoutView; // @synthesize secondaryLayoutView=_secondaryLayoutView;
@property(retain) DVTBorderedView *primaryLayoutView; // @synthesize primaryLayoutView=_primaryLayoutView;
- (void)revertComparisonEditorStateWithDictionary:(id)arg1;
- (void)commitComparisonEditorStateToDictionary:(id)arg1;
- (BOOL)comparisonEditorShouldCloseDocumentsDuringWillOpenSpecifier:(id)arg1;
- (void)comparisonEditor:(id)arg1 didReplaceAncestorDocument:(id)arg2;
- (void)comparisonEditor:(id)arg1 didReplaceSecondaryDocument:(id)arg2;
- (void)comparisonEditor:(id)arg1 didReplacePrimaryDocument:(id)arg2;
- (void)_setupEditorForPrimaryOrMergeDocument:(id)arg1;
- (id)currentSelectedDocumentLocations;
- (id)currentSelectedItems;
- (void)hideSecondaryPlaceholder;
- (void)showSecondaryPlaceholder;
- (void)hidePrimaryPlaceholder;
- (void)showPrimaryPlaceholder;
- (double)splitView:(id)arg1 constrainSplitPosition:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (void)splitViewDidResizeSubviews:(id)arg1;
- (id)_fileTextSettings;
- (void)showEmptySecondaryEditor:(id)arg1;
- (void)showEmptyPrimaryEditor:(id)arg1;
- (void)_willOpenSpecifier:(id)arg1;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)invalidate;
- (void)loadView;
- (void)_syncStructureDocument;
- (void)_initializeDiffSession;
- (void)_tearDownDiffSession;
- (void)_saveMergeState;
- (void)_resetMergeState;
- (id)_windowForError;
@property(readonly) IDESourceControlConflictMergeData *previousMergeData;
@property(retain) DVTDiffSession *diffSession;
@property(retain) IDEEditor *secondaryEditor; // @synthesize secondaryEditor=_secondaryEditor;
@property(retain) IDEEditor *primaryEditor; // @synthesize primaryEditor=_primaryEditor;
@property(readonly) QLPreviewView *secondaryQuickLookView;
@property(readonly) QLPreviewView *primaryQuickLookView;
- (id)keyEditor;
- (void)comparisonContextMenu_copyDiff:(id)arg1;

@end

@interface IDEApplication (IDEQuickLookDocumentScripting)
- (void)setSdefSupport_activeBlueprintDocument:(id)arg1;
- (id)sdefSupport_activeBlueprintDocument;
- (id)sdefSupport_blueprintDocuments;
@end

@interface IDEFileReference (IDEQuickLookImageInspector)
- (id)uistring_mediaCodecs;
- (id)uistring_mediaAudioChannels;
- (id)uistring_mediaDuration;
- (id)uistring_imageHasAlphaChannel;
- (id)uistring_imageColorSpace;
- (id)uistring_imageResolution;
- (id)uistring_imageDimensions;
- (struct __MDItem *)_spotlightItemCopy;
@end

