/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDESubversion.ideplugin/Contents/MacOS/IDESubversion
 * UUID: 3DF7F03F-0A16-3EF3-96EF-3FBFB7032FC0
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 2058.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol IDESourceControlProtocol <NSObject>
- (id)operationForRequest:(id)arg1;
- (BOOL)authenticationRequiredForRequest:(id)arg1;
- (BOOL)validateRequest:(id)arg1 error:(id *)arg2;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@optional
- (id)debugDescription;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface SVNController : NSObject <IDESourceControlProtocol>
{
}

- (id)operationForRequest:(id)arg1;
- (BOOL)authenticationRequiredForRequest:(id)arg1;
- (BOOL)validateRequest:(id)arg1 error:(id *)arg2;

@end

@interface SVNOperation : IDESourceControlTaskOperation
{
}

- (int)statusValueForRepositoryStringValue:(id)arg1;
- (int)statusValueForWorkingCopyStringValue:(id)arg1 isCopied:(BOOL)arg2;
- (unsigned long long)propertyStatusValueForWorkingCopyStringValue:(id)arg1;
- (id)defaultArguments;
- (void)sanitizeFilenames;
- (id)pathFromErrorMessage:(id)arg1;
- (id)errorFromErrorMessage:(id)arg1;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNAddOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNBlameOperation : SVNOperation
{
    NSDateFormatter *_formatter;
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNCommitOperation : SVNOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNCurrentBranchOperation : SVNOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNCopyOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNMakeDirectoryOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNMergeOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNMoveOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNRemoveOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNResolveOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNRevertOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNPropSetOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNPropDelOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNPropGetOperation : SVNOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNIgnoreOperation : IDESourceControlOperation
{
    NSOperationQueue *_operationQueue;
}

@property(retain) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void)main;

@end

@interface SVNStatusOperation : SVNOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNSwitchOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNUpdateOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

@interface SVNDiffOperation : SVNOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNExportFileOperation : SVNOperation
{
    DVTFilePath *_exportedFilePath;
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNListOperation : SVNOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNCheckoutOperation : SVNOperation
{
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNInfoOperation : SVNOperation
{
    NSDateFormatter *_formatter;
}

- (void)parseData;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNLogOperation : SVNOperation
{
    NSDateFormatter *_formatter;
}

- (void)parseData;
- (unsigned long long)statusValueForRepositoryShortStringValue:(id)arg1;
- (id)initWithRequest:(id)arg1;

@end

@interface SVNImportOperation : SVNOperation
{
}

- (id)initWithRequest:(id)arg1;

@end

