/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/IDETemplateLibrary.ideplugin/Contents/MacOS/IDETemplateLibrary
 * UUID: 1A1327B9-854C-3B1B-ABC7-7CE4958328C2
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1165.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@interface IDEFileTemplatesLibrary : DVTLibraryController
{
    BOOL _isLibraryPopulated;
    NSArray *_orderedPlatformFamilies;
}

- (void)populatePasteboard:(id)arg1 withAssets:(id)arg2;
- (void)libraryDidLoad;
- (id)templateSections;
- (id)allValidPlatforms;
- (void)addLibraryGroupsIfNeeded;
- (id)platformIconForPlatformFamily:(id)arg1;
- (id)defaultPlatformIcon;

@end

@interface IDEFileTemplateChooserAssistant : IDETemplateChooserAssistant
{
}

+ (id)supportedTemplateKind;

@end

@interface IDEFileTemplateCompletionAssistant : IDETemplateCompletionAssistant
{
}

@end

