/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/PlugIns/ScriptingDefinitionEditor.ideplugin/Contents/MacOS/ScriptingDefinitionEditor
 * UUID: FC5E5354-201E-3676-83AF-B53C510FDB2F
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 2052.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Required
 */

@protocol DVTBasicFindBarFindable <DVTFindBarFindable>
- (BOOL)basicFindBar:(id)arg1 findPreviousByWrapping:(BOOL)arg2;
- (BOOL)basicFindBar:(id)arg1 findNextByWrapping:(BOOL)arg2;
- (long long)basicFindBar:(id)arg1 findString:(id)arg2 caseSensitive:(BOOL)arg3 withFindType:(unsigned long long)arg4 andMatchStyle:(int)arg5;
- (BOOL)basicFindBar:(id)arg1 supportsMatchStyle:(int)arg2;
- (BOOL)basicFindBar:(id)arg1 supportsFindType:(unsigned long long)arg2;

@optional
- (void)basicFindBarLostFocus:(id)arg1;
@end

@protocol DVTFindBarFindable

@optional
- (struct _NSRange)selectedRangeForFindBar:(id)arg1;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateResults:(id)arg2;
@end

@protocol IDEDocumentStructureProviding <NSObject>
@property(readonly) NSArray *ideTopLevelStructureObjects;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;

@optional
- (id)debugDescription;
@end

@protocol NSUserInterfaceValidations
- (BOOL)validateUserInterfaceItem:(id)arg1;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface IDEScriptingDefinitionPlaceholderView : DVTLayoutView_ML
{
    NSTextField *_placeholderTextField;
}

- (void)layoutBottomUp;
@property(copy) NSString *placeholderString;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface IDEScriptingDefinitionEditor : IDEEditor <DVTBasicFindBarFindable, NSUserInterfaceValidations>
{
    NSView *_dictionaryView;
    WebView *_dictionaryWebView;
    OSADictionaryController *_dictionaryController;
    NSSegmentedControl *_navigationControl;
    NSSegmentedControl *_textSizeControl;
    NSSegmentedControl *_viewModeControl;
    NSSearchField *_searchField;
    BOOL _delayedSelectionUpdate;
    NSString *_findString;
    BOOL _findCaseSensitive;
}

+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (id)keyPathsForValuesAffectingCurrentSelectedItems;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)basicFindBarLostFocus:(id)arg1;
- (BOOL)basicFindBar:(id)arg1 findPreviousByWrapping:(BOOL)arg2;
- (BOOL)basicFindBar:(id)arg1 findNextByWrapping:(BOOL)arg2;
- (long long)basicFindBar:(id)arg1 findString:(id)arg2 caseSensitive:(BOOL)arg3 withFindType:(unsigned long long)arg4 andMatchStyle:(int)arg5;
- (BOOL)basicFindBar:(id)arg1 supportsMatchStyle:(int)arg2;
- (BOOL)basicFindBar:(id)arg1 supportsFindType:(unsigned long long)arg2;
- (id)createFindBar;
- (BOOL)findBarSupported;
- (void)useSelectionForReplace:(id)arg1;
- (void)useSelectionForFind:(id)arg1;
- (void)changeSearch:(id)arg1;
- (void)goBackForward:(id)arg1;
- (void)changeViewMode:(id)arg1;
- (void)scriptingDefinition_browseInheritance:(id)arg1;
- (void)scriptingDefinition_browseContainment:(id)arg1;
- (void)scriptingDefinition_browseSuites:(id)arg1;
- (void)changeTextSize:(id)arg1;
- (void)scriptingDefinition_makeTextSmaller:(id)arg1;
- (void)scriptingDefinition_makeTextLarger:(id)arg1;
@property int viewMode;
- (void)selectDocumentLocations:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_updateSelectedDefinitions;
- (id)currentSelectedDocumentLocations;
- (id)currentSelectedItems;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)takeFocus;
- (void)loadView;
- (void)_setUpContentView;

@end

@interface IDEScriptingDefinitionDocument : IDEEditorDocument <IDEDocumentStructureProviding>
{
    OSADictionary *_dictionary;
    NSMutableArray *_editors;
}

+ (BOOL)autosavesInPlace;
- (id)definitionForDocumentLocation:(id)arg1;
@property(readonly) NSArray *ideTopLevelStructureObjects;
@property(readonly) OSADictionary *dictionary;
- (void)printDocument:(id)arg1;
- (BOOL)readFromData:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)updateChangeCount:(unsigned long long)arg1;
- (id)dataOfType:(id)arg1 error:(id *)arg2;
- (BOOL)prepareSavePanel:(id)arg1;
- (BOOL)writeToURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

@end

@interface IDEScriptingDefinitionDocumentLocation : DVTDocumentLocation
{
    NSString *suiteCode;
    NSString *commandOrClassCode;
    NSString *elementOrPropertyCode;
}

@property(readonly) NSString *elementOrPropertyCode; // @synthesize elementOrPropertyCode;
@property(readonly) NSString *commandOrClassCode; // @synthesize commandOrClassCode;
@property(readonly) NSString *suiteCode; // @synthesize suiteCode;
- (id)initWithDocumentURL:(id)arg1 timestamp:(id)arg2 definition:(id)arg3;

@end

@interface OSADefinition (IDEScriptingDefinitionItem)
- (id)scriptingDefinition_childDefinitions;
- (id)navigableItem_contentDocumentLocationInDocumentURL:(id)arg1;
- (id)navigableItem_documentType;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (id)ideModelObjectTypeIdentifier;
@end

@interface OSASuiteDefinition (IDEScriptingDefinitionItem)
- (id)scriptingDefinition_childDefinitions;
- (id)ideModelObjectTypeIdentifier;
@end

@interface OSAClassDefinition (IDEScriptingDefinitionItem)
- (id)scriptingDefinition_childDefinitions;
- (id)ideModelObjectTypeIdentifier;
@end

@interface OSADefinition (IDEScriptingDefinitionDocumentLocation)
- (id)documentLocation_elementOrPropertyCode;
- (id)documentLocation_commandOrClassCode;
- (id)documentLocation_suiteCode;
- (id)documentLocation_code;
@end

@interface OSASuiteDefinition (IDEScriptingDefinitionDocumentLocation)
- (id)documentLocation_suiteCode;
- (id)documentLocation_code;
@end

@interface OSACommandDefinition (IDEScriptingDefinitionDocumentLocation)
- (id)documentLocation_commandOrClassCode;
@end

@interface OSAClassDefinition (IDEScriptingDefinitionDocumentLocation)
- (id)documentLocation_commandOrClassCode;
- (id)documentLocation_code;
- (id)_extendedClassDefinition;
@end

@interface OSAElementDefinition (IDEScriptingDefinitionDocumentLocation)
- (id)documentLocation_elementOrPropertyCode;
- (id)documentLocation_commandOrClassCode;
- (id)documentLocation_classDefinition;
@end

@interface OSAPropertyDefinition (IDEScriptingDefinitionDocumentLocation)
- (id)documentLocation_elementOrPropertyCode;
- (id)documentLocation_commandOrClassCode;
- (id)documentLocation_classDefinition;
@end

