/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark -

/*
 * File: /Applications/Xcode.app/Contents/SharedFrameworks/DVTDeveloperModeHelper.framework/Versions/A/DVTDeveloperModeHelper
 * UUID: 21A6F1C8-65DD-3E61-AED0-E68B58D7B4C2
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1.0.0, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Supported
 */

@interface DVTDeveloperModeHelper : NSObject
{
}

- (id)_stringForFileHandleData:(id)arg1;
- (void)setDeveloperModeEnabled:(BOOL)arg1;
- (BOOL)isDeveloperModeEnabled;

@end

@interface DVTDeveloperModeAlertHelper : NSObject
{
    NSWindow *_parentWindow;
    int _messageType;
    id _completionHandler;
    DVTDeveloperModeHelper *_developerModeHelper;
}

+ (void)askToEnableDeveloperModeIfNecessary:(id)arg1 messageType:(int)arg2 completionHandler:(id)arg3;
+ (void)initialize;
- (void)_alertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
@property(readonly) NSString *informativeText;
- (void)_askToEnableDeveloperModeIfNecessary;
- (BOOL)_shouldAskUserAboutDeveloperMode;
- (void)dealloc;
- (id)_initWithParentWindow:(id)arg1 messageType:(int)arg2 completionHandler:(id)arg3;

@end

